// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: rusprofile_lookup.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inn string `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
}

func (x *CompanyInfoRequest) Reset() {
	*x = CompanyInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rusprofile_lookup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyInfoRequest) ProtoMessage() {}

func (x *CompanyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rusprofile_lookup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyInfoRequest.ProtoReflect.Descriptor instead.
func (*CompanyInfoRequest) Descriptor() ([]byte, []int) {
	return file_rusprofile_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyInfoRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type CompanyInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inn          string `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp          string `protobuf:"bytes,2,opt,name=kpp,proto3" json:"kpp,omitempty"`
	CompanyName  string `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	DirectorName string `protobuf:"bytes,4,opt,name=director_name,json=directorName,proto3" json:"director_name,omitempty"`
}

func (x *CompanyInfoResponse) Reset() {
	*x = CompanyInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rusprofile_lookup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyInfoResponse) ProtoMessage() {}

func (x *CompanyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rusprofile_lookup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyInfoResponse.ProtoReflect.Descriptor instead.
func (*CompanyInfoResponse) Descriptor() ([]byte, []int) {
	return file_rusprofile_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *CompanyInfoResponse) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *CompanyInfoResponse) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *CompanyInfoResponse) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CompanyInfoResponse) GetDirectorName() string {
	if x != nil {
		return x.DirectorName
	}
	return ""
}

var File_rusprofile_lookup_proto protoreflect.FileDescriptor

var file_rusprofile_lookup_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x75, 0x73, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x22, 0x26, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x22, 0x81, 0x01, 0x0a, 0x13, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x69, 0x6e, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x70, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x70, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x5f, 0x0a,
	0x12, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15,
	0x5a, 0x13, 0x49, 0x4e, 0x4e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rusprofile_lookup_proto_rawDescOnce sync.Once
	file_rusprofile_lookup_proto_rawDescData = file_rusprofile_lookup_proto_rawDesc
)

func file_rusprofile_lookup_proto_rawDescGZIP() []byte {
	file_rusprofile_lookup_proto_rawDescOnce.Do(func() {
		file_rusprofile_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(file_rusprofile_lookup_proto_rawDescData)
	})
	return file_rusprofile_lookup_proto_rawDescData
}

var file_rusprofile_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rusprofile_lookup_proto_goTypes = []interface{}{
	(*CompanyInfoRequest)(nil),  // 0: protos.CompanyInfoRequest
	(*CompanyInfoResponse)(nil), // 1: protos.CompanyInfoResponse
}
var file_rusprofile_lookup_proto_depIdxs = []int32{
	0, // 0: protos.CompanyInfoService.GetCompanyInfo:input_type -> protos.CompanyInfoRequest
	1, // 1: protos.CompanyInfoService.GetCompanyInfo:output_type -> protos.CompanyInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rusprofile_lookup_proto_init() }
func file_rusprofile_lookup_proto_init() {
	if File_rusprofile_lookup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rusprofile_lookup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rusprofile_lookup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rusprofile_lookup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rusprofile_lookup_proto_goTypes,
		DependencyIndexes: file_rusprofile_lookup_proto_depIdxs,
		MessageInfos:      file_rusprofile_lookup_proto_msgTypes,
	}.Build()
	File_rusprofile_lookup_proto = out.File
	file_rusprofile_lookup_proto_rawDesc = nil
	file_rusprofile_lookup_proto_goTypes = nil
	file_rusprofile_lookup_proto_depIdxs = nil
}
